greenpeace/planet4-child-theme-switzerland

js/gpch-child.js, src/scss/layout/_post_types.scss
Posts in archived pages are now styled like the article list with colored tags, black titles, full width text.
=> 164: Improved styling of archive pages

src/scss/layout/_navigation-bar.scss
https://tickets.greenpeace.ch/view.php?id=266
=> 266: Restyled mobile menu

src/scss/blocks/_core-heading.scss
https://tickets.greenpeace.ch/view.php?id=107
=> 107: Overwrite Planet4 section header styles

includes/custom-post-types.php, includes/gutenberg-blocks.php, includes/post-templates/gpch-event-single.php, includes/user-roles.php, src/scss/layout/_header.scss, src/scss/layout/_post_types.scss, templates/single-gpch_event.twig
Creates a new post type gpch_event that has additional fields for time and place. Also the needed templates for single view and a user role that only has access to events is included.
=> 270: Events functionality: Post type, templates, user roles

src/scss/layout/_elements.scss
By reverting master theme style changes.
=> 309: Fixed button width

admin/js/editor.js, functions.php
Overwriting some of the global configurations on styles added through planet4-plugin-gutenberg-blocks.
=> 310: Gutenberg block style update

src/scss/layout/_elements.scss
Column and button block missing bottom margin fixed.
=> 316: Fixes style issues from Wordpress 5.3 update

js/gpch-child.js, src/scss/variables/_colors.scss
Tag name was changed from "nutrition" to "alimentation"
=> 321: Added "alimentation" to the list of tags with climate color scheme

js/gpch-child.js, src/scss/blocks/_p4-campaign-covers.scss
Class name has changed in the block, updating class names to match.
=> 325: Fix for broken campaign covers block

src/scss/blocks/_core-separator.scss, src/scss/blocks/_gravity-forms.scss
- Separator block max width
- Gravity Forms headings
=> 371: Corrected styling issues

functions.php, includes/advanced-post-settings.php
Allows to output a noindex meta tag in posts and pages.
=> 299: Add advanced option to output noindex meta tag

includes/user-roles.php
User with the new role can view and edit drafts, but not publish.
=> 400: Add an additional user role for content feedback

functions.php, includes/gravity-forms-extensions.php, js/gpch-child.js
Using an AJAX call makes sure no cached data is used for the form prefill.
=> 415: Replace server side prefill by AJAX call

src/scss/blocks/_core-button.scss
- Removed rounded corners introduced in master theme
- Removed uppercase formatting in buttons consistently (accessibility)
=> 427: Fix button style regression bugs

classes/GPCH_Inxmail_API.php
Bugfix in regex handling
Bugfix, use the string not the whole array
Rearrange error message of set_flags
=> Updated error message for set_flags and some code cleanup

src/scss/editor-style.scss, src/scss/editor/_editor.scss
Mainly fix YT video embed block in editor
=> 467: Update admin styles

admin/js/editor.js, src/scss/blocks/_core-button.scss
Added "secondary" and "highlight" button styles.
=> 478: Add additional button styles

includes/gravity-forms-extensions.php
As a setting in Gravity Forms settings and sent to Inxmail for newsletter subscriptions.
=> 529: Add Sextant ProjectUID

src/scss/layout/_layout.scss
Resize the image to the same width as the post content.
=> P4-38: Resize post header image

includes/gravity-forms-extensions.php
Much more forgiving validation to also accept phone formats we can clean up in our ETL tool. Also removed the mask that was caused confusion with form autofill.
=> P4-8: Update phone number formats

src/scss/blocks/_p4_posts-list.scss
As a temporary solution until we can add the post type instead.
=> ES-175: Hide category in related posts list

includes/gravity-forms-extensions.php
Disallow numbers in first_name and last_name fields in GravityForms.
=> ES-27: Validate numbers in name fields
